### ISSUE TITLE
Error loading Window icon

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#15]
Display try to load icon from .jar file.

``` java
java.io.FileNotFoundException: file:\C:\..\..\Voxel-0.0.4-ALPHA\lib\Voxel-0.0.4-ALPHA.jar!\assets\icon\icon32.png (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at io.github.guerra24.voxel.client.kernel.graphics.opengl.Display.loadIcon(Display.java:413)
        at io.github.guerra24.voxel.client.kernel.graphics.opengl.Display.startUp(Display.java:341)
        at io.github.guerra24.voxel.client.kernel.core.Kernel.init(Kernel.java:85)
        at io.github.guerra24.voxel.client.kernel.core.Kernel.mainLoop(Kernel.java:125)
        at io.github.guerra24.voxel.client.kernel.core.Kernel.<init>(Kernel.java:77)
        at io.github.guerra24.voxel.client.kernel.bootstrap.Bootstrap.main(Bootstrap.java:119)
```

**Comment by Guerra24** [comment]
Fixed in Build 84.
