### ISSUE TITLE
Ramdomly UpdateChunksRender gets NullPointerException

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#21]
In random moment the "Voxel Thread" gets a NullPointerException

``` java
Exception in thread "Voxel Main" java.lang.NullPointerException
    at io.github.guerra24.voxel.client.kernel.world.DimensionalWorld.updateChunksRender(DimensionalWorld.java:247)
    at io.github.guerra24.voxel.client.kernel.core.Kernel.render(Kernel.java:172)
    at io.github.guerra24.voxel.client.kernel.core.Kernel.mainLoop(Kernel.java:151)
    at io.github.guerra24.voxel.client.kernel.core.Kernel.<init>(Kernel.java:88)
    at io.github.guerra24.voxel.client.kernel.bootstrap.Bootstrap.main(Bootstrap.java:119)
```

**Comment by Guerra24** [comment]
Fixed in an unknown commit.
