### ISSUE TITLE
"-autostart" causes NullPointerException

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#44]
Random NullPointerException in the switch from "Loading Screen" to "GameSP", Causes by the "-autostart" flag.

``` java
Exception in thread "Voxel Main" java.lang.NullPointerException
    at net.guerra24.voxel.client.graphics.shaders.ShaderProgram.loadVector(ShaderProgram.java:218)
    at net.guerra24.voxel.client.graphics.shaders.EntityShader.loadLightPosition(EntityShader.java:125)
    at net.guerra24.voxel.client.graphics.MasterRenderer.begin(MasterRenderer.java:164)
    at net.guerra24.voxel.client.core.states.GameSPState.render(GameSPState.java:64)
    at net.guerra24.voxel.client.core.GlobalStates.doRender(GlobalStates.java:55)
    at net.guerra24.voxel.client.core.Voxel.render(Voxel.java:166)
    at net.guerra24.voxel.client.core.Voxel.mainLoop(Voxel.java:153)
    at net.guerra24.voxel.client.core.Voxel.<init>(Voxel.java:72)
    at net.guerra24.voxel.client.bootstrap.Bootstrap.main(Bootstrap.java:119)
```

**Comment by Guerra24** [comment]
Fixed
