### ISSUE TITLE
net.luxvacuos.voxel.client.core.exception.CompileShaderException: 0(22) : error C0204: version directive must be first statement and may not be repeated

### ISSUE THREAD

**Issue by Wolftein** [Guerra24/Voxel#73]
Hello!, i just found your project and when i tried to run it from your snapshot launcher got an exception.

```
Voxel has crashed, please report this in the Forum or GitHub Repo

## System Info
Voxel Version: 0.0.10-develop-d9a920b
Molten API Version: 0.0.2
Build: 6
Running on: Windows 10 AMD64
LWJGL Version: 3.0.0 build 90
GLFW Version: 3.2.0 Win32 WGL EGL VisualC DLL
OpenGL Version: 3.3.0 NVIDIA 368.22
Vulkan Version: No Available
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 570/PCIe/SSE2

## StackTrace
net.luxvacuos.voxel.client.core.exception.CompileShaderException: 0(22) : error C0204: version directive must be first statement and may not be repeated

    at net.luxvacuos.voxel.client.rendering.api.opengl.shaders.ShaderProgram.loadShader(ShaderProgram.java:329)
    at net.luxvacuos.voxel.client.rendering.api.opengl.shaders.ShaderProgram.<init>(ShaderProgram.java:105)
    at net.luxvacuos.voxel.client.rendering.api.opengl.shaders.EntityBasicShader.<init>(EntityBasicShader.java:36)
    at net.luxvacuos.voxel.client.rendering.api.opengl.MasterShadowRenderer.<init>(MasterShadowRenderer.java:52)
    at net.luxvacuos.voxel.client.resources.GameResources.init(GameResources.java:135)
    at net.luxvacuos.voxel.client.core.Voxel.init(Voxel.java:107)
    at net.luxvacuos.voxel.client.core.Voxel.mainLoop(Voxel.java:125)
    at net.luxvacuos.voxel.client.core.Voxel.<init>(Voxel.java:63)
    at net.luxvacuos.voxel.client.bootstrap.Bootstrap.main(Bootstrap.java:119)
```

**Comment by Guerra24** [comment]
I already seen this bug in older versions and i believed that was fixed, fix in the next commit also thanks for the report :D
