### ISSUE TITLE
Intel HD Graphics Incompatbility 

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#89]
All related to Intel HD incompatibly issues.
Extensions:
- [x] ~~ARB_shading_language_include~~ <-- nVidia-only extension 
- [x] ~~White screen on HD Graphics 4600~~ <-- Won't Fix
- [ ] Broken Ambient Occlusion

Please submit the crashlog (either in a pastie/pastebin or here) and what version of chipset you are using (Intel HD 3k, 4k, etc)

**Comment by matiuri** [comment]
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] Starting Client
...
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] Voxel Client Version: Development Version
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] Running on: LINUX_64
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] LWJGL Version: 3.1.0 build 40
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] GLFW Version: 3.3.0 X11 GLX EGL clock_gettime /dev/js Xf86vm shared
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] OpenGL Version: 3.3 (Core Profile) **Mesa 11.2.0**
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] Vendor: **Intel Open Source Technology Center**
[INFO  2016/12/26 16:34:41 PM] [Voxel-Client] Renderer: **Mesa DRI Intel(R) Haswell Desktop** 
...
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] 
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Registering State: Splash_Screen
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Loading NVGTexture: LuxVacuos-Logo.png
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] ModLoader Init phase
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] ModLoader Post Init phase
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Setting current state to Splash_Screen
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] StateMachine running
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Registering State: About
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Loading NVGTexture: Voxel-Logo.png
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Registering State: Main_Menu
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Compiling: test
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Registering State: Options
[INFO  2016/12/26 16:34:42 PM] [Voxel-Client] Registering State: SP_Create_World
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Registering State: SP_Loading
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Registering State: SP_Pause
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Registering State: SP_Selection
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Registering State: Test
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Loading Shader to GL-VFS: /common/common.glsl
java.lang.IllegalStateException: This function is not available.
        at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:94)
        at org.lwjgl.opengl.ARBShadingLanguageInclude.nglNamedStringARB(ARBShadingLanguageInclude.java:105)
        at org.lwjgl.opengl.ARBShadingLanguageInclude.glNamedStringARB(ARBShadingLanguageInclude.java:140)
        at **net.luxvacuos.voxel.client.rendering.api.opengl.shaders.ShaderProgram.loadToVFS(ShaderProgram.java:85)
        at net.luxvacuos.voxel.client.core.states.TestState.init(TestState.java:115)
        at net.luxvacuos.voxel.universal.core.states.StateMachine.registerState(StateMachine.java:54)
        at net.luxvacuos.voxel.client.core.Voxel.lambda$init$7(Voxel.java:164)
        at net.luxvacuos.voxel.universal.core.TaskManager.update(TaskManager.java:39)
        at net.luxvacuos.voxel.client.core.Voxel.loop(Voxel.java:214)
        at net.luxvacuos.voxel.client.core.Voxel.build(Voxel.java:194)
        at net.luxvacuos.voxel.client.core.Voxel.<init>(Voxel.java:85)
        at net.luxvacuos.voxel.client.bootstrap.Bootstrap.main(Bootstrap.java:116)**
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Registering State: Crash
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Loading NVGFont: Px437_IBM_VGA8.ttf
[INFO  2016/12/26 16:34:43 PM] [Voxel-Client] Setting current state to Crash

This comment was edited by @HACKhalo2 to highlight relevant information to the bug

**Comment by jlitewski** [comment]
@matiuri what Intel chipset do you have?

**Comment by matiuri** [comment]
@HACKhalo2 I'm not completely sure, but I think it's an Intel HD Graphics 4600

**Comment by jlitewski** [comment]
@matiuri that works and is what I was looking for. Thank you.

Do you have access to a Windows machine with the same chipset to make sure it isn't a Mesa issue?

**Comment by matiuri** [comment]
@HACKhalo2 Yes, my computer is dual-booted. However, I won't boot Windows now because it's a waste of time, as I'm running Linux. I'll check that tomorrow when I turn on the computer again.

**Comment by matiuri** [comment]
@HACKhalo2 I've just run Voxel in Windows. Here is the output of gradlew.bat run:

:utils:compileJava UP-TO-DATE
:utils:processResources UP-TO-DATE
:utils:classes UP-TO-DATE
:utils:jar UP-TO-DATE
:ashley:compileJava UP-TO-DATE
:ashley:processResources UP-TO-DATE
:ashley:classes UP-TO-DATE
:ashley:jar UP-TO-DATE
:assets:compileJava UP-TO-DATE
:assets:processResources UP-TO-DATE
:assets:classes UP-TO-DATE
:assets:jar UP-TO-DATE
:universal:compileJava UP-TO-DATE
:universal:processResources UP-TO-DATE
:universal:classes UP-TO-DATE
:universal:jar UP-TO-DATE
:client:compileJava UP-TO-DATE
:client:processResources UP-TO-DATE
:client:classes UP-TO-DATE
:client:run
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Starting Client
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Creating WindowHandle for 'Voxel'
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] PixelBufferHandle [redBits=16, redBitsAccum=0, greenBits=16, greenBitsAccum=0, blueBits
=16, blueBitsAccum=0, alphaBits=8, alphaBitsAccum=0, depthBits=32, stencilBits=8, auxBuffers=0, samples=0, refreshRate=-1, stereo=fal
se, srgbCapable=true, doubleBuffer=true]
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Creating new Window 'Voxel'
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 32
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 32
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 32
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 32
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 64
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 64
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Roboto-Bold.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Roboto-Regular.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Poppins-Regular.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Poppins-Light.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Poppins-Medium.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Poppins-Bold.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Poppins-SemiBold.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading NVGFont: Entypo.ttf
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Voxel Client Version: Development Version
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Running on: WINDOWS_64
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] LWJGL Version: 3.1.1 build 16
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] GLFW Version: 3.3.0 Win32 WGL EGL VisualC DLL
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] OpenGL Version: 3.3.0 - Build 20.19.15.4531
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] GLSL Version: 3.30 - Build 20.19.15.4531
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Vendor: Intel
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Renderer: Intel(R) HD Graphics 4600
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Starting Mods Load
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] ModLoader Pre Init phase
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading Texture: def/d.png
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading Texture: def/d_n.png
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 256
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 256
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading Texture: def/d_r.png
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading Texture: def/d_m.png
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Loading Texture: def/d_s.png
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image width: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image height: 512
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image components: 4
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Image HDR: false
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] 
[INFO  2017/01/02 11:51:00 AM] [Voxel-Client] Starting up SoundSystem...
[INFO  2017/01/02 11:51:00 AM] [CommandThread] Initializing LWJGL OpenAL
[INFO  2017/01/02 11:51:00 AM] [CommandThread]     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[INFO  2017/01/02 11:51:00 AM] [CommandThread] OpenALC10: true
[INFO  2017/01/02 11:51:00 AM] [CommandThread] OpenALC11: true
[INFO  2017/01/02 11:51:00 AM] [CommandThread] caps.ALC_EXT_EFX = true
[INFO  2017/01/02 11:51:00 AM] [CommandThread] 0: OpenAL Soft on Altavoces (Realtek High Definition Audio)
[INFO  2017/01/02 11:51:00 AM] [CommandThread] 1: OpenAL Soft on Realtek Digital Output (Realtek High Definition Audio)
[INFO  2017/01/02 11:51:00 AM] [CommandThread] Default device: OpenAL Soft
[INFO  2017/01/02 11:51:00 AM] [CommandThread] ALC_FREQUENCY: 48000Hz
[INFO  2017/01/02 11:51:00 AM] [CommandThread] ALC_REFRESH: 50Hz
[INFO  2017/01/02 11:51:00 AM] [CommandThread] ALC_SYNC: false
[INFO  2017/01/02 11:51:00 AM] [CommandThread] ALC_MONO_SOURCES: 255
[INFO  2017/01/02 11:51:00 AM] [CommandThread] ALC_STEREO_SOURCES: 1
[INFO  2017/01/02 11:51:00 AM] [CommandThread] OpenAL initialized.
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] 
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Registering State: Splash_Screen
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Loading NVGTexture: LuxVacuos-Logo.png
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] ModLoader Init phase
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] ModLoader Post Init phase
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Setting current state to Splash_Screen
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] StateMachine running
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Registering State: About
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Loading NVGTexture: Voxel-Logo.png
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Registering State: Main_Menu
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Compiling: test
.\gradlew.bat : java.lang.NullPointerException
En línea: 1 Carácter: 1
+ .\gradlew.bat run
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (java.lang.NullPointerException:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at net.luxvacuos.voxel.universal.core.Scripting.compile(Scripting.java:62)
	at net.luxvacuos.voxel.client.core.states.MainMenuState.init(MainMenuState.java:114)
	at net.luxvacuos.voxel.universal.core.states.StateMachine.registerState(StateMachine.java:54)
	at net.luxvacuos.voxel.client.core.Voxel.lambda$init$1(Voxel.java:162)
	at net.luxvacuos.voxel.universal.core.TaskManager.update(TaskManager.java:39)
	at net.luxvacuos.voxel.client.core.Voxel.loop(Voxel.java:218)
	at net.luxvacuos.voxel.client.core.Voxel.build(Voxel.java:198)
	at net.luxvacuos.voxel.client.core.Voxel.<init>(Voxel.java:87)
	at net.luxvacuos.voxel.client.bootstrap.Bootstrap.main(Bootstrap.java:116)
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Registering State: Crash
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Loading NVGFont: Px437_IBM_VGA8.ttf
[INFO  2017/01/02 11:51:01 AM] [Voxel-Client] Setting current state to Crash
[INFO  2017/01/02 11:51:09 AM] [Voxel-Client] Cleaning Resources
[INFO  2017/01/02 11:51:09 AM] [Voxel-Client] 
[INFO  2017/01/02 11:51:09 AM] [Voxel-Client] SoundSystem shutting down...
[INFO  2017/01/02 11:51:09 AM] [Voxel-Client]     Author: Paul Lamb, www.paulscode.com
[INFO  2017/01/02 11:51:09 AM] [Voxel-Client] 
[INFO  2017/01/02 11:51:09 AM] [Voxel-Client] Cleaning Resources for: 19683296
:launcher:compileJava UP-TO-DATE
:launcher:processResources UP-TO-DATE
:launcher:classes UP-TO-DATE
:launcher:run
[INFO  2017/01/02 11:51:09 AM] [Voxel-Launcher-Bootstrap] Version: 0.0.12
[INFO  2017/01/02 11:51:09 AM] [Voxel-Launcher-Bootstrap] Dist Server: https://s3.luxvacuos.net
[INFO  2017/01/02 11:51:09 AM] [Voxel-Launcher-Bootstrap] Auth Server: https://luxvacuos.net
java.lang.StringIndexOutOfBoundsException: String index out of range: 4
	at java.lang.String.substring(String.java:1963)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawString(WCGraphicsPrismContext.java:960)
	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:290)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:102)
	at com.sun.webkit.graphics.WCImage.flushRQ(WCImage.java:52)
	at com.sun.javafx.webkit.prism.RTImage.lambda$getPixelBuffer$77(RTImage.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:745)
java.lang.StringIndexOutOfBoundsException: String index out of range: 7
	at java.lang.String.substring(String.java:1963)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawString(WCGraphicsPrismContext.java:960)
	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:290)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:102)
	at com.sun.webkit.graphics.WCImage.flushRQ(WCImage.java:52)
	at com.sun.javafx.webkit.prism.RTImage.lambda$getPixelBuffer$77(RTImage.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:745)
java.lang.StringIndexOutOfBoundsException: String index out of range: 6
	at java.lang.String.substring(String.java:1963)
	at com.sun.javafx.webkit.prism.WCGraphicsPrismContext.drawString(WCGraphicsPrismContext.java:960)
	at com.sun.webkit.graphics.GraphicsDecoder.decode(GraphicsDecoder.java:290)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:91)
	at com.sun.webkit.graphics.WCRenderQueue.decode(WCRenderQueue.java:102)
	at com.sun.webkit.graphics.WCImage.flushRQ(WCImage.java:52)
	at com.sun.javafx.webkit.prism.RTImage.lambda$getPixelBuffer$77(RTImage.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:745)
:server:compileJava UP-TO-DATE
:server:processResources UP-TO-DATE
:server:classes UP-TO-DATE
:server:run

BUILD SUCCESSFUL

Total time: 21.891 secs

**Comment by jlitewski** [comment]
@matiuri I found the cause of this issue. ARB_shading_language_include is a nVidia-only extension, and it will cause other platforms to crash. I've began working on a custom implementation that will fix all of these issues. Thank you for testing, though! I greatly appreciated it.

**Comment by jlitewski** [comment]
@matiuri could I have you test the newest commit and report your findings?

**Comment by matiuri** [comment]
@HACKhalo2 There isn't any crash, but I think the game is too white:
![screenshot_20170103_131317](https://cloud.githubusercontent.com/assets/11176122/21614000/74dc1ba8-d1e0-11e6-8552-f61b851e3e09.png)
I've run Voxel in Linux.

**Comment by matiuri** [comment]
The screen isn't white in Windows. Furthermore, the shaders work well.

**Comment by jlitewski** [comment]
Closing for now, will reopen if more issues come up with the Intel chipsets
